services:
  mongodb:
    image: mongo:latest
    container_name: jobladder
    ports:
      - 27017:27017  
    volumes:
      - mongo_volume:/data/db
  api:
    image: api
    depends_on:
      - mongodb
    build: 
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - MONGO_URI=mongodb://mongodb:27017/jobladder
  ui:
    image: frontend
    depends_on:
      - api
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
volumes:
  mongo_volume:
